#!/bin/bash

# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`
SCRIPTPATH=`echo "$SCRIPTPATH" | sed -E 's@^\\n@@'`

SCOPE="src"

source $SCRIPTPATH/lib/echo-color.lib.sh

case "$1" in
	build )

		${SCRIPTPATH}/util/build.sh

		;;

	git )

		if [[ `which git | wc -l` -eq 1 ]]; then
			shift
			echo ""
			echo_info "Executando comando git em '$SCRIPTPATH': "
			echo ""
			# echo "$(cd $SCRIPTPATH && pwd)"
			# export LANG="en_US.UTF-8" 
			cd $SCRIPTPATH && LANG=en_US git $@
		else
			echo ""
			echo_error "Precisa instalar o git!"
			echo ""
		fi

		;;

	dev )

		shift
		echo_color $COLOR_LIGHT_RED "Modo dev \n"
		FILE=`[[ $(grep -E "\.sh\$" <<< "$1" | wc -l) -eq 1 ]] && echo "$1" || echo "${1}.sh"`
		if [[ -f ${SCRIPTPATH}/${FILE} ]]; then
			shift
			#echo "${SCRIPTPATH}/${FILE} $@"
			bash ${SCRIPTPATH}/${FILE} $@
		elif [[ "$1" != "" ]]; then
			echo_error "O comando '$1' não existe nesta suite hunter."
		fi

		;;

	* )

		if [ \( "$1" != "" \) -a \( `ls -p "${SCRIPTPATH}/${SCOPE}/" | grep -E "^${1}(.sh)?\\$" | wc -l` -eq 1 \) ]; then
			FILE=`[[ $(grep -E "\.sh\$" <<< "$1" | wc -l) -eq 1 ]] && echo "$1" || echo "${1}.sh"`
			shift
			#echo "${SCRIPTPATH}/${SCOPE}/${FILE} $@"
			${SCRIPTPATH}/${SCOPE}/./${FILE} $@
		else
			echo ""
			echo_error "O comando '$1' não existe nesta suite hunter."
			echo ""
		fi

		;;
esac
